/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerVendeBitcoin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Investidor;

/**
 *
 * @author victo
 */
public class VendeBitcoin extends javax.swing.JFrame {

    /**
     * Creates new form VendeBitcoin
     */
    public VendeBitcoin(Investidor investidor) {
        initComponents();
        this.investidor=investidor ;
        controller = new ControllerVendeBitcoin(this, investidor);
        lblBitcoin.setText(String.valueOf(investidor.getCarteira().getMoedas().get(1).getSaldo()));
        double cotacaobitcoin = investidor.getCotacao().getCotacaobitcoin();
        double saldorealembitcoin = investidor.getCarteira().getMoedas().get(1).getSaldo() * cotacaobitcoin;

        // Atualize o lblRealBitcoin com o valor calculado
        lblRealBitcoin.setText(String.format("R$ %.2f", saldorealembitcoin));
        
        
        
    }

    public Investidor getInvestidor() {
        return investidor;
    }

    public void setInvestidor(Investidor investidor) {
        this.investidor = investidor;
    }

    public ControllerVendeBitcoin getController() {
        return controller;
    }

    public void setController(ControllerVendeBitcoin controller) {
        this.controller = controller;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JButton getJbjVenda() {
        return jbjVenda;
    }

    public void setJbjVenda(JButton jbjVenda) {
        this.jbjVenda = jbjVenda;
    }

    public JLabel getLblBitcoin() {
        return lblBitcoin;
    }

    public void setLblBitcoin(JLabel lblBitcoin) {
        this.lblBitcoin = lblBitcoin;
    }

    public JLabel getLblRealBitcoin() {
        return lblRealBitcoin;
    }

    public void setLblRealBitcoin(JLabel lblRealBitcoin) {
        this.lblRealBitcoin = lblRealBitcoin;
    }

    public JTextField getTxtVendaReal() {
        return txtVendaReal;
    }

    public void setTxtVendaReal(JTextField txtVendaReal) {
        this.txtVendaReal = txtVendaReal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBitcoin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRealBitcoin = new javax.swing.JLabel();
        txtVendaReal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbjVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o qunato voce quer vende de bitcoin em real");

        jLabel2.setText("Seu saldo de bitcoin :");

        lblBitcoin.setText("--------------------------------");

        jLabel3.setText("trasnformando seu saldo de bitcoin para real :");

        lblRealBitcoin.setText("-----------------------------");

        txtVendaReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendaRealActionPerformed(evt);
            }
        });

        jLabel4.setText("digite  quanto voce quer vende de bitcoin em real:");

        jbjVenda.setText("Venda");
        jbjVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbjVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRealBitcoin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblBitcoin))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbjVenda)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(txtVendaReal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBitcoin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblRealBitcoin))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVendaReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(60, 60, 60)
                .addComponent(jbjVenda)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVendaRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendaRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendaRealActionPerformed

    private void jbjVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbjVendaActionPerformed
        controller.vendeBitcoin();
    }//GEN-LAST:event_jbjVendaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VendeBitcoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VendeBitcoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VendeBitcoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VendeBitcoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VendeBitcoin().setVisible(true);
//            }
//        });
//    }
    
   private Investidor investidor;
   private ControllerVendeBitcoin controller;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbjVenda;
    private javax.swing.JLabel lblBitcoin;
    private javax.swing.JLabel lblRealBitcoin;
    private javax.swing.JTextField txtVendaReal;
    // End of variables declaration//GEN-END:variables
}
